### ISSUE TITLE
Typeerror on running

### ISSUE THREAD

**Issue by sj7272** [SafetyCulture/iauditor-exporter#4]
Running in Windows Bash shell using Python 3.8
config file below

```
$ python exporter.py --format sql
2020-02-16 18:02:46 hades exporter_logger[29880] CRITICAL Exception parsing export_inactive_items from the configuration file, defaulting to True
2020-02-16 18:02:46 hades exporter_logger[29880] CRITICAL 'export_inactive_items'
Traceback (most recent call last):
  File "exporter.py", line 1471, in <module>
    main()
  File "exporter.py", line 1461, in main
    sync_exports(logger, settings, sc_client)
  File "exporter.py", line 980, in sync_exports
    list_of_audits = sc_client.discover_audits(modified_after=last_successful,completed=completed_setting,archived=archived_setting)
TypeError: discover_audits() got an unexpected keyword argument 'archived'
```

```
API:
    token: <mytoken>
config_name: iauditor
export_options:
    export_path: data
    timezone:
    filename:
    export_archived: false
    export_completed: both
    use_real_template_name: true
    csv_options: 
        export_inactive_items: true
    export_profiles:
    template_ids: 
    sync_delay_in_seconds: 900
    media_sync_offset_in_seconds: 0
    allow_table_creation: true
    merge_rows: false
    actions_merge_rows: false
    sql_table: iauditor_data
    database_type: mssql+pyodbc_mssql
    database_user: <myuser>
    database_pwd: <mypwd>
    database_server: <myserver>
    database_port: 1433
    database_schema: dbo
    database_name: <mydb>?driver=ODBC Driver 17 for SQL Server
```

**Comment by eddabrahamsen** [comment]
Thanks for raising the issue. It looks like you haven’t uninstalled the old version of our SDK. Try running ```

pip uninstall safetyculture-sdk-python

```
Then try installing again. I’ve put together a load of documentation here, too: https://safetyculture.github.io/iauditor-exporter/install-intros/quick-install/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sj7272** [comment]
Thanks Ed, I tried but get the same
Thx,
Simon

**Comment by eddabrahamsen** [comment]
The error you’re receiving is definitely due to the old version of the SDK as it didn’t include support for exporting archived inspections. 

I wonder if the new install of the SDK isn’t overwriting the old one. What if you force the install? So from the directory with the script. cd into safetyculture-sdk-python and run:

`pip install --force-reinstall .`

Being sure you have the . on the end so it uses the directory rather than trying to get the old version from PyPi.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sj7272** [comment]
No, given there's no readme, I'm not sure what's happening here.
Simon

```
sj727@hades MINGW64 /d/src/iaudw/iauditor-exporter/safetyculture-sdk-python (master)
$ pip install --force-reinstall .

Processing d:\src\iaudw\iauditor-exporter\safetyculture-sdk-python
    ERROR: Command errored out with exit status 1:
     command: 'd:\progs\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sj727\\AppData\\Local\\Temp\\pip-req-build-efgb6ihi\\setup.py'"'"'; __file__='"'"'C:\\Users\\sj727\\AppData\\Local\\Temp\\pip-req-build-efgb6ihi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sj727\AppData\Local\Temp\pip-req-build-efgb6ihi\pip-egg-info'
         cwd: C:\Users\sj727\AppData\Local\Temp\pip-req-build-efgb6ihi\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sj727\AppData\Local\Temp\pip-req-build-efgb6ihi\setup.py", line 19, in <module>
        long_description=open('README.md', 'r').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by eddabrahamsen** [comment]
Hey Simon, did you close this intentionally? I've isolated the above issue - I'd been cleaning up the repo but didn't realise a couple of files were still reference in the setup file. I'll get some changes pushed today and that should resolve this.

**Comment by sj7272** [comment]
Sorry, finger trouble (and late nights!) - Thought I closed the response!
No worries, will look again tonight

**Comment by eddabrahamsen** [comment]
Hey @sj7272 , this should be sorted now. I've made some additional changes (including publishing the new SDK to PyPi rather than installing it manually) which should make this more straightforward. Can I ask that you do a fresh clone/download of the repo, populate a new config file (there's some minor formatting changes) and try again? Updated install instructions are here too: https://safetyculture.github.io/iauditor-exporter/install-intros/quick-install/

**Comment by sj7272** [comment]
Thanks @eddabrahamsen - will try over the weekend

**Comment by MightyMirko** [comment]
Hello, 


got the same issue: 
```
(iAuditor) :/mnt/c/Users/<myuser>/coding/00_work/iAuditor/iauditor-exporter$ p3 exporter.py --format csv
Traceback (most recent call last):
  File "exporter.py", line 1511, in <module>
    main()
  File "exporter.py", line 1501, in main
    sync_exports(logger, settings, sc_client)
  File "exporter.py", line 1002, in sync_exports
    list_of_audits = sc_client.discover_audits(modified_after=last_successful,completed=completed_setting,archived=archived_setting)
TypeError: discover_audits() got an unexpected keyword argument 'archived'
....
...

(iAuditor) mnt/c/Users/<myuser>/coding/00_work/iAuditor/iauditor-exporter$ pip install -U safetyculture-sdk-python
Requirement already up-to-date: safetyculture-sdk-python in /mnt/c/Users/<myuser>/coding/00_work/iAuditor/venv/iAuditor/lib/python3.6/site-packages (4.1.1)

```

**Comment by eddabrahamsen** [comment]
Hey @MightyMirko , in the requirements.txt file, the package is actually safetyculture-sdk-python-beta - try removing safetyculture-sdk-python then installing safetyculture-sdk-python-beta
